/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "apic2ccac19",
            "endpoint": "https://1u1612yhgk.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:b188a335-9ccf-49bf-a447-c1259f3cd5d8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_QBFWpeKZh",
    "aws_user_pools_web_client_id": "2upgi7gmmjni6s25083ua88n8c",
    "oauth": {}
};


export default awsmobile;
